### ISSUE TITLE
Confusing Onboarding Activities

### ISSUE THREAD

**Issue by djcouto** [kairoscorp/adamastor#17]
As a develop I find the `onboarding activities` class names too confusing. 
I have to actually get in them read some code to understand the meaning of them and what onboarding screen they are related two. It will very cool if someone could just refactor this, and make the respective _layouts_ and maybe put this last in a folder too.

My suggestion:
- `Onboard1Activity` -> `Onboard1WelcomeActivity`
- `Onboard2Activity` -> `Onboard2LocationActivity`
- `Onboard3Activity` -> `Onboard3ContextAppsActivity`
- `Onboard4Activity` -> `Onboard4ScheduleActivity`

The numbers are just to preserve the onboarding flow order.

**Comment by jlsilva1994** [comment]
you have a point here, it was my mistake so i will fix this.
