### ISSUE TITLE
[AppsByContext] Error rendering apps after editing context apps

### ISSUE THREAD

**Issue by jlsilva1994** [kairoscorp/adamastor#53]
when we add or remove apps from the context, the list is not presenting the apps right...

**Comment by Hugainz** [comment]
Do you have any idea why this is happening? I remember testing this and it worked. Has anything changed in the Settings ?

**Comment by Hugainz** [comment]
I have a fix for this, but it's really just a bad way to do it. I'll try to come up with something better.

**Comment by hgg** [comment]
I have a fix for this :+1: will add it to the PR to fix the apps in the main screen.
